# Generated by Django 3.2.3 on 2021-05-20 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VyasProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', tinymce.models.HTMLField()),
                ('Date_started', models.DateField()),
                ('Date_ended', models.DateField(blank=True)),
                ('Category', models.CharField(choices=[('award', 'Award'), ('favourite', 'Favourite'), ('code', 'Code'), ('community', 'Community')], default='Community', max_length=30)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
