# Generated by Django 2.2.12 on 2021-02-10 19:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VyasProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', tinymce.models.HTMLField()),
                ('Date_started', models.DateTimeField()),
                ('Date_ended', models.DateTimeField(null=True)),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
    ]
