# Generated by Django 2.2.12 on 2021-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210210_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyasprofile',
            name='Category',
            field=models.CharField(choices=[('award', 'Award'), ('favourite', 'Favourite'), ('code', 'Code'), ('community', 'Community')], default='Community', max_length=30),
        ),
    ]
