# Generated by Django 2.2.12 on 2021-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210211_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='vyasprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='logos'),
        ),
    ]
