# Generated by Django 2.2.12 on 2021-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_vyasprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyasprofile',
            name='Date_ended',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
