# Generated by Django 2.2.12 on 2021-02-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210129_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
