# Generated by Django 2.2.12 on 2021-02-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210206_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Slug_Field',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
